import { db } from "../firebase";
import {
  collection,
  addDoc,
  getDocs,
  serverTimestamp
} from "firebase/firestore";

// Add a new work log entry to a project
export async function addWorkLog(projectId, { mins, secs }) {
  const workLogRef = collection(db, "projects", projectId, "workLog");
  const entry = await addDoc(workLogRef, {
    mins,
    secs,
    seconds: mins * 60 + secs, // Calculates total seconds to add up for total progress
    loggedAt: serverTimestamp() // Firebase records the current time based on its own time
  });
  return entry.id; // Returns an autogenerated ID to whatever called this function
}

// Get all work log entries for a project
export async function getWorkLog(projectId) {
  const workLogRef = collection(db, "projects", projectId, "workLog");
  const workLogSnap = await getDocs(workLogRef);
  return workLogSnap.docs.map((doc) => ({ id: doc.id, ...doc.data() }));
}